set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

#set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc-14)
#set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++-14)

set(CMAKE_C_COMPILER "/usr/bin/aarch64-linux-gnu-gcc-14")
set(CMAKE_CXX_COMPILER "/usr/bin/aarch64-linux-gnu-g++-14")

set(CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_SYSROOT /sysroot)
set(CMAKE_FIND_ROOT_PATH /sysroot)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
